name: CI
on:
  push:

# Fix workflows triggered by dependabot https://github.com/dependabot/dependabot-core/issues/3253
permissions:
  checks: write

jobs:
  lint-rb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - name: StandardRB Linter
        run: bundle exec standardrb

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: yarn
      - name: Install npm packages
        run: yarn
      - name: StandardJS Linter
        run: yarn lint

  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - name: Install gems
        run: |
          gem install brakeman -v 6.1.2
      - name: Brakeman Static Code Analysis
        run: bundle exec brakeman --no-exit-on-warn --no-exit-on-error

  test-rb:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: yarn
      - name: Install Node dependencies
        run: yarn
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - name: Setup test database
        run: bin/rails db:create db:schema:load db:migrate RAILS_ENV=test
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432"
      - name: Build ESbuild
        run: yarn build
      - name: Build PostCSS
        run: yarn build:css
      - name: Run tests
        run: bundle exec rspec
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432"
          MSJ_API_URL: "https://agents.mon-suivi-justice.incubateur.net/api/v1"
