name: CI
on:
  push:

# Fix workflows triggered by dependabot https://github.com/dependabot/dependabot-core/issues/3253
permissions:
  pull-requests: write


jobs:
  lint-rb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: StandardRB Linter
        run: bundle exec standardrb

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: yarn
      - name: Install npm packages
        run: yarn
      - name: StandardJS Linter
        run: yarn lint

  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Brakeman Static Code Analysis
        uses: devmasx/brakeman-linter-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  test-rb:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Node environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: yarn
      - name: Install Node dependencies
        run: yarn
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Setup test database
        run: bin/rails db:create db:schema:load db:migrate RAILS_ENV=test
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432"
      - name: Run tests
        run: bundle exec rspec
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432"
          MSJ_API_URL: "https://agents.mon-suivi-justice.incubateur.net/api/v1"
